name = "video-site"
compatibility_date = "2025-08-11"
main = "worker.js"

[assets]
directory = "."
binding = "ASSETS"

# Environment variables will be set in the Cloudflare Workers dashboard
# Use [secrets] section for sensitive data like API keys