name = "videohub"
compatibility_date = "2024-08-11"
main = "src/index.js"

[assets]
directory = "."

[env.production]
name = "videohub-production"

[env.staging]
name = "videohub-staging"
